---
- name: install postgresql
  yum: name={{ item }} state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2

- name: postgresql initdb
  shell: service postgresql initdb
         creates=/var/lib/pgsql/data/postgresql.conf

- name: start postgresql
  service: name=postgresql state=started
  sudo: yes

- name: service
  service: name=postgresql state=running enabled=yes

- name: postgresql.conf copy
  template: src=postgresql.conf dest=/var/lib/pgsql/data/postgresql.conf
  notify: restart postgresql

- name: pg_hba.conf copy
  template: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf
  notify: restart postgresql

- name: postgres user sudores
  lineinfile: 
    dest: /etc/sudoers.d/postgres 
    owner: root
    group: root
    mode: 0440
    line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name : create database
  postgresql_db: 
    name: "{{ postgresql.db_name }}"
    encoding: "UTF-8"
    login_user: postgres
  sudo_user: postgres
  sudo: yes

- name: create user
  postgresql_user: 
    db: "{{ postgresql.db_name }}"
    name: "{{ postgresql.db_user }}"
    password: "{{ postgresql.db_pass }}"
    priv: ALL
    state: present
    login_user: postgres
  sudo_user: postgres
  sudo: yes

