spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  add-application-context-header: false # disable X-Application-Context
  contextPath: /management
  port: 8000
server:
  port: 80
  contextPath: /app
  session-timeout: 900
security:
  basic:
    enabled: false
# http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints
endpoints:
  endpoints.sensitive: true
  actuator.enabled: false
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: true
  env.enabled: false
  health.enabled: true
  info.enabled: false
  logfile.enabled: false
  metrics.enabled: true
  mappings.enabled: false
  shutdown.enabled: false
  trace.enabled: false
